# This is a basic workflow to help you get started with Actions

name: CI - Chewie Job1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '45 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo "Hello World, I'm Chewie!"

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
          
      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Running main.py
        env:
          bot_id: ${{ secrets.BOT_ID }}
          chat_id: ${{ secrets.CHAT_ID }}
          test_secret: ${{ secrets.TEST_SECRET }}
        run: |
          python main.py

      - name: Publishing results to GitHub
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: '' #optional defaults to master
