# This is a basic workflow to help you get started with Actions

name: CI - Chewie WorkFlow 2 - Trade

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  #  path:
  #    - '**/tds.csv'
  #pull_request:
  #  branches: [ main ]
  #schedule:
  #  - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PERSONAL_GITHUB_TOKEN}}

      - name: Installing Python 3.9.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
          
      - name: Installing requirements3
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements3.txt
#          pip install TA-Lib

      - name: Running job2.py
        env:
          bot_id: ${{ secrets.BOT_ID }}
          chat_id: ${{ secrets.CHAT_ID }}
          test_secret: ${{ secrets.TEST_SECRET }}
        run: |
          python job2.py

      - name: Update counter and commit
        run: |
          ./recursive/check_counter_and_commit.sh
